FROM ubuntu:14.04

RUN \
  apt-get update && \
  apt-get -y upgrade &&\
  apt-get install -y build-essential &&
  rm -rf /var/lib/apt/lists/*


COPY pingpong/PingServer.java pingpong/PingServer.java
COPY pingpong/PingServerFactory.java pingpong/PingServerFactory.java
COPY pingpong/client/PingClient.java pingpong/client/PingClient.java
COPY Makefile /Makefile

RUN make
