FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y openjdk-7-jdk
COPY pingpong/PingServer.java pingpong/PingServer.java
COPY pingpong/PingServerFactory.java pingpong/PingServerFactory.java
COPY pingpong/server/PServer.java pingpong/server/PServer.java
COPY rmi/ rmi/

RUN javac /pingpong/server/PServer.java
ENTRYPOINT java pingpong.server.PServer 8000
