FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y openjdk-7-jdk
COPY pingpong/PingServer.java pingpong/PingServer.java
COPY pingpong/PingServerFactory.java pingpong/PingServerFactory.java
COPY pingpong/client/PingClient.java pingpong/client/PingClient.java
COPY rmi/ rmi/

RUN javac /pingpong/client/PingClient.java
